#pragma once

/* PRESSURE LIMITS (ml H2O)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_PRESSURE 0
#define DEFAULT_MINIMUM_PRESSURE 50
#define MAXIMUM_MINIMUM_PRESSURE 200
#define MINIMUM_MAXIMUM_PRESSURE 50
#define DEFAULT_MAXIMUM_PRESSURE 400
#define MAXIMUM_PRESSURE 600

#define PLATEAU_AIRWAY_PRESSURE_INCREMENT 10
#define DEFAULT_PLATEAU_AIRWAY_PRESSURE 300

/* MINUTE VENTILATION LIMITS (ml/min)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_MINUTE_VENTILATION 1000
#define DEFAULT_MINIMUM_MINUTE_VENTILATION 5000
#define MAXIMUM_MINIMUM_MINUTE_VENTILATION 6000
#define MINIMUM_MAXIMUM_MINUTE_VENTILATION 3000
#define DEFAULT_MAXIMUM_MINUTE_VENTILATION 10000 
#define MAXIMUM_MINUTE_VENTILATION 30000
#define MINUTE_VENTILATION_INCREMENT 100

/* VOLUME LIMITS (ml)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_VOLUME 150
#define DEFAULT_MINIMUM_VOLUME 180
#define MINIMUM_MAXIMUM_VOLUME 200
#define DEFAULT_MAXIMUM_VOLUME 750
#define VOLUME_INCREMENT 5

#define DEFAULT_TIDAL_VOLUME 450

/* RESPIRATORY RATE (bpm)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_RESPIRATORY_RATE 10
#define DEFAULT_RESPIRATORY_RATE 12
#define MAXIMUM_RESPIRATORY_RATE 20

/* RESPIRATORY RATIO (1:x)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_RESPIRATORY_RATIO 1
#define DEFAULT_RESPIRATORY_RATIO 3
#define MAXIMUM_RESPIRATORY_RATIO 5

/* TRIGGER PRESSURE (ml H2O)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_TRIGGER_PRESSURE 0
#define DEFAULT_TRIGGER_PRESSURE 15
#define MAXIMUM_TRIGGER_PRESSURE 50

/* INSPIRATORY FLOW (l/min)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_INSPIRATORY_FLOW 10
#define DEFAULT_INSPIRATORY_FLOW 35
#define MAXIMUM_INSPIRATORY_FLOW 60

/* EXPIRATORY FLOW (l/min)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_EXPIRATORY_FLOW 10
#define DEFAULT_EXPIRATORY_FLOW 35
#define MAXIMUM_EXPIRATORY_FLOW 60

/* START POSITION (steps)
 * * * * * * * * * * * * * * * * */
#define MINIMUM_START_POSITION 500
#define DEFAULT_START_POSITION 1000
#define MAXIMUM_START_POSITION 5000
#define START_POSITION_INCREMENT 100

/* FULL_PRESS_VOLUME
 * * * * * * * * * * * * * * * * */
#define MINIMUM_FULL_PRESS_VOLUME 450
#define DEFAULT_FULL_PRESS_VOLUME 450
#define MAXIMUM_FULL_PRESS_VOLUME 850
#define FULL_PRESS_VOLUME_INCREMENT 10

/* FULL_PRESS_VOLUME
 * * * * * * * * * * * * * * * * */
#define FIRST_POSITION_PRESSURE 10
#define FIRST_POSITION_VOLUME 300

#define SECOND_POSITION_PRESSURE 20
#define SECOND_POSITION_VOLUME 400
